#ifndef __USERMSG__
#define __USERMSG__

// Counterstrike
int hLogo(const char *pszName, int iSize, void *pbuf);
int hResetHUD(const char *pszName, int iSize, void *pbuf);
int hGameMode(const char *pszName, int iSize, void *pbuf);
int hInitHUD(const char *pszName, int iSize, void *pbuf);
int hViewMode(const char *pszName, int iSize, void *pbuf);
int hSetFOV(const char *pszName, int iSize, void *pbuf);
int hHLTV(const char *pszName, int iSize, void *pbuf);
int hSpecHealth(const char *pszName, int iSize, void *pbuf);
int hConcuss(const char *pszName, int iSize, void *pbuf);
int hReloadSound(const char *pszName, int iSize, void *pbuf);
int hBombDrop(const char *pszName, int iSize, void *pbuf);
int hBombPickup(const char *pszName, int iSize, void *pbuf);
int hADStop(const char *pszName, int iSize, void *pbuf);
int hHostagePos(const char *pszName, int iSize, void *pbuf);
int hHostageK(const char *pszName, int iSize, void *pbuf);
int hCZCareerHUD(const char *pszName, int iSize, void *pbuf);
int hShadowIdx(const char *pszName, int iSize, void *pbuf);
int hBotVoice(const char *pszName, int iSize, void *pbuf);
int hBrass(const char *pszName, int iSize, void *pbuf);
int hFog(const char *pszName, int iSize, void *pbuf);
int hShowTimer(const char *pszName, int iSize, void *pbuf);
int hTeamNames(const char *pszName, int iSize, void *pbuf);
int hFeign(const char *pszName, int iSize, void *pbuf);
int hDetpack(const char *pszName, int iSize, void *pbuf);
int hMOTD(const char *pszName, int iSize, void *pbuf);
int hBuildSt(const char *pszName, int iSize, void *pbuf);
int hRandomPC(const char *pszName, int iSize, void *pbuf);
int hServerName(const char *pszName, int iSize, void *pbuf);
int hScoreInfo(const char *pszName, int iSize, void *pbuf);
int hTeamScore(const char *pszName, int iSize, void *pbuf);
int hTeamInfo(const char *pszName, int iSize, void *pbuf);
int hLocation(const char *pszName, int iSize, void *pbuf);
int hSpectator(const char *pszName, int iSize, void *pbuf);
int hAllowSpec(const char *pszName, int iSize, void *pbuf);
int hForceCam(const char *pszName, int iSize, void *pbuf);
int hVGUIMenu(const char *pszName, int iSize, void *pbuf);
int hTutorText(const char *pszName, int iSize, void *pbuf);
int hTutorLine(const char *pszName, int iSize, void *pbuf);
int hTutorState(const char *pszName, int iSize, void *pbuf);
int hTutorClose(const char *pszName, int iSize, void *pbuf);
int hBuyClose(const char *pszName, int iSize, void *pbuf);
int hSpecHealth2(const char *pszName, int iSize, void *pbuf);
int hBotProgress(const char *pszName, int iSize, void *pbuf);
int hNVGToggle(const char *pszName, int iSize, void *pbuf);
int hCurWeapon(const char *pszName, int iSize, void *pbuf);
int hWeaponList(const char *pszName, int iSize, void *pbuf);
int hAmmoPickup(const char *pszName, int iSize, void *pbuf);
int hWeapPickup(const char *pszName, int iSize, void *pbuf);
int hItemPickup(const char *pszName, int iSize, void *pbuf);
int hHideWeapon(const char *pszName, int iSize, void *pbuf);
int hAmmoX(const char *pszName, int iSize, void *pbuf);
int hCrosshair(const char *pszName, int iSize, void *pbuf);
int hHealth(const char *pszName, int iSize, void *pbuf);
int hDamage(const char *pszName, int iSize, void *pbuf);
int hRadar(const char *pszName, int iSize, void *pbuf);
int hScoreAttrib(const char *pszName, int iSize, void *pbuf);
int hClCorpse(const char *pszName, int iSize, void *pbuf);
int hReceiveW(const char *pszName, int iSize, void *pbuf);
int hSayText(const char *pszName, int iSize, void *pbuf);
int hSendAudio(const char *pszName, int iSize, void *pbuf);
int hGeiger(const char *pszName, int iSize, void *pbuf);
int hTrain(const char *pszName, int iSize, void *pbuf);
int hBattery(const char *pszName, int iSize, void *pbuf);
int hArmorType(const char *pszName, int iSize, void *pbuf);
int hFlashlight(const char *pszName, int iSize, void *pbuf);
int hFlashBat(const char *pszName, int iSize, void *pbuf);
int hHudText(const char *pszName, int iSize, void *pbuf);
int hHudTextPro(const char *pszName, int iSize, void *pbuf);
int hHudTextArgs(const char *pszName, int iSize, void *pbuf);
int hGameTitle(const char *pszName, int iSize, void *pbuf);
int hStatusText(const char *pszName, int iSize, void *pbuf);
int hStatusValue(const char *pszName, int iSize, void *pbuf);
int hDeathMsg(const char *pszName, int iSize, void *pbuf);
int hSecAmmoVal(const char *pszName, int iSize, void *pbuf);
int hSecAmmoIcon(const char *pszName, int iSize, void *pbuf);
int hTextMsg(const char *pszName, int iSize, void *pbuf);
int hStatusIcon(const char *pszName, int iSize, void *pbuf);
int hMoney(const char *pszName, int iSize, void *pbuf);
int hBlinkAcct(const char *pszName, int iSize, void *pbuf);
int hRoundTime(const char *pszName, int iSize, void *pbuf);
int hBarTime(const char *pszName, int iSize, void *pbuf);
int hBarTime2(const char *pszName, int iSize, void *pbuf);
int hTaskTime(const char *pszName, int iSize, void *pbuf);
int hScenario(const char *pszName, int iSize, void *pbuf);
int hShowMenu(const char *pszName, int iSize, void *pbuf);
int hVoiceMask(const char *pszName, int iSize, void *pbuf);
int hReqState(const char *pszName, int iSize, void *pbuf);

extern pfnUserMsgHook pLogo;
extern pfnUserMsgHook pResetHUD;
extern pfnUserMsgHook pGameMode;
extern pfnUserMsgHook pInitHUD;
extern pfnUserMsgHook pViewMode;
extern pfnUserMsgHook pSetFOV;
extern pfnUserMsgHook pHLTV;
extern pfnUserMsgHook pSpecHealth;
extern pfnUserMsgHook pConcuss;
extern pfnUserMsgHook pReloadSound;
extern pfnUserMsgHook pBombDrop;
extern pfnUserMsgHook pBombPickup;
extern pfnUserMsgHook pADStop;
extern pfnUserMsgHook pHostagePos;
extern pfnUserMsgHook pHostageK;
extern pfnUserMsgHook pCZCareerHUD;
extern pfnUserMsgHook pShadowIdx;
extern pfnUserMsgHook pBotVoice;
extern pfnUserMsgHook pBrass;
extern pfnUserMsgHook pFog;
extern pfnUserMsgHook pShowTimer;
extern pfnUserMsgHook pTeamNames;
extern pfnUserMsgHook pFeign;
extern pfnUserMsgHook pDetpack;
extern pfnUserMsgHook pMOTD;
extern pfnUserMsgHook pBuildSt;
extern pfnUserMsgHook pRandomPC;
extern pfnUserMsgHook pServerName;
extern pfnUserMsgHook pScoreInfo;
extern pfnUserMsgHook pTeamScore;
extern pfnUserMsgHook pTeamInfo;
extern pfnUserMsgHook pLocation;
extern pfnUserMsgHook pSpectator;
extern pfnUserMsgHook pAllowSpec;
extern pfnUserMsgHook pForceCam;
extern pfnUserMsgHook pVGUIMenu;
extern pfnUserMsgHook pTutorText;
extern pfnUserMsgHook pTutorLine;
extern pfnUserMsgHook pTutorState;
extern pfnUserMsgHook pTutorClose;
extern pfnUserMsgHook pBuyClose;
extern pfnUserMsgHook pSpecHealth2;
extern pfnUserMsgHook pBotProgress;
extern pfnUserMsgHook pNVGToggle;
extern pfnUserMsgHook pCurWeapon;
extern pfnUserMsgHook pWeaponList;
extern pfnUserMsgHook pAmmoPickup;
extern pfnUserMsgHook pWeapPickup;
extern pfnUserMsgHook pItemPickup;
extern pfnUserMsgHook pHideWeapon;
extern pfnUserMsgHook pAmmoX;
extern pfnUserMsgHook pCrosshair;
extern pfnUserMsgHook pHealth;
extern pfnUserMsgHook pDamage;
extern pfnUserMsgHook pRadar;
extern pfnUserMsgHook pScoreAttrib;
extern pfnUserMsgHook pClCorpse;
extern pfnUserMsgHook pReceiveW;
extern pfnUserMsgHook pSayText;
extern pfnUserMsgHook pSendAudio;
extern pfnUserMsgHook pGeiger;
extern pfnUserMsgHook pTrain;
extern pfnUserMsgHook pBattery;
extern pfnUserMsgHook pArmorType;
extern pfnUserMsgHook pFlashlight;
extern pfnUserMsgHook pFlashBat;
extern pfnUserMsgHook pHudText;
extern pfnUserMsgHook pHudTextPro;
extern pfnUserMsgHook pHudTextArgs;
extern pfnUserMsgHook pGameTitle;
extern pfnUserMsgHook pStatusText;
extern pfnUserMsgHook pStatusValue;
extern pfnUserMsgHook pDeathMsg;
extern pfnUserMsgHook pSecAmmoVal;
extern pfnUserMsgHook pSecAmmoIcon;
extern pfnUserMsgHook pTextMsg;
extern pfnUserMsgHook pStatusIcon;
extern pfnUserMsgHook pMoney;
extern pfnUserMsgHook pBlinkAcct;
extern pfnUserMsgHook pRoundTime;
extern pfnUserMsgHook pBarTime;
extern pfnUserMsgHook pBarTime2;
extern pfnUserMsgHook pTaskTime;
extern pfnUserMsgHook pScenario;
extern pfnUserMsgHook pShowMenu;
extern pfnUserMsgHook pVoiceMask;
extern pfnUserMsgHook pReqState;

// Day of defeat
int hYouDied(const char *pszName, int iSize, void *pbuf);
int hBloodPuff(const char *pszName, int iSize, void *pbuf);
int hHandSignal(const char *pszName, int iSize, void *pbuf);
int hUseSound(const char *pszName, int iSize, void *pbuf);
int hScoreInfoLong(const char *pszName, int iSize, void *pbuf);
int hMapMarker(const char *pszName, int iSize, void *pbuf);
int hWaveTime(const char *pszName, int iSize, void *pbuf);
int hWaveStatus(const char *pszName, int iSize, void *pbuf);
int hWideScreen(const char *pszName, int iSize, void *pbuf);
int hFrags(const char *pszName, int iSize, void *pbuf);
int hObjScore(const char *pszName, int iSize, void *pbuf);
int hPStatus(const char *pszName, int iSize, void *pbuf);
int hScoreShort(const char *pszName, int iSize, void *pbuf);
int hPClass(const char *pszName, int iSize, void *pbuf);
int hPTeam(const char *pszName, int iSize, void *pbuf);
int hRoundState(const char *pszName, int iSize, void *pbuf);
int hCurMarker(const char *pszName, int iSize, void *pbuf);
int hTimeLeft(const char *pszName, int iSize, void *pbuf);
int hScope(const char *pszName, int iSize, void *pbuf);
int hGameRules(const char *pszName, int iSize, void *pbuf);
int hCameraView(const char *pszName, int iSize, void *pbuf);
int hResetSens(const char *pszName, int iSize, void *pbuf);
int hObject(const char *pszName, int iSize, void *pbuf);
int hClientAreas(const char *pszName, int iSize, void *pbuf);
int hInitObj(const char *pszName, int iSize, void *pbuf);
int hSetObj(const char *pszName, int iSize, void *pbuf);
int hStartProg(const char *pszName, int iSize, void *pbuf);
int hStartProgF(const char *pszName, int iSize, void *pbuf);
int hProgUpdate(const char *pszName, int iSize, void *pbuf);
int hCancelProg(const char *pszName, int iSize, void *pbuf);
int hTimerStatus(const char *pszName, int iSize, void *pbuf);
int hPlayersIn(const char *pszName, int iSize, void *pbuf);
int hPShoot(const char *pszName, int iSize, void *pbuf);
int hAmmoShort(const char *pszName, int iSize, void *pbuf);
int hReloadDone(const char *pszName, int iSize, void *pbuf);
int hCapMsg(const char *pszName, int iSize, void *pbuf);
int hClanTimer(const char *pszName, int iSize, void *pbuf);

extern pfnUserMsgHook pYouDied;
extern pfnUserMsgHook pBloodPuff;
extern pfnUserMsgHook pHandSignal;
extern pfnUserMsgHook pUseSound;
extern pfnUserMsgHook pScoreInfoLong;
extern pfnUserMsgHook pMapMarker;
extern pfnUserMsgHook pWaveTime;
extern pfnUserMsgHook pWaveStatus;
extern pfnUserMsgHook pWideScreen;
extern pfnUserMsgHook pFrags;
extern pfnUserMsgHook pObjScore;
extern pfnUserMsgHook pPStatus;
extern pfnUserMsgHook pScoreShort;
extern pfnUserMsgHook pPClass;
extern pfnUserMsgHook pPTeam;
extern pfnUserMsgHook pRoundState;
extern pfnUserMsgHook pCurMarker;
extern pfnUserMsgHook pTimeLeft;
extern pfnUserMsgHook pScope;
extern pfnUserMsgHook pGameRules;
extern pfnUserMsgHook pCameraView;
extern pfnUserMsgHook pResetSens;
extern pfnUserMsgHook pObject;
extern pfnUserMsgHook pClientAreas;
extern pfnUserMsgHook pInitObj;
extern pfnUserMsgHook pSetObj;
extern pfnUserMsgHook pStartProg;
extern pfnUserMsgHook pStartProgF;
extern pfnUserMsgHook pProgUpdate;
extern pfnUserMsgHook pCancelProg;
extern pfnUserMsgHook pTimerStatus;
extern pfnUserMsgHook pPlayersIn;
extern pfnUserMsgHook pPShoot;
extern pfnUserMsgHook pAmmoShort;
extern pfnUserMsgHook pReloadDone;
extern pfnUserMsgHook pCapMsg;
extern pfnUserMsgHook pClanTimer;

// Deathmatch classic
int hQItems(const char *pszName, int iSize, void *pbuf);
extern pfnUserMsgHook pQItems;

// Halflife
int hValClass(const char *pszName, int iSize, void *pbuf);
int hSpecFade(const char *pszName, int iSize, void *pbuf);
int hResetFade(const char *pszName, int iSize, void *pbuf);
int hBench(const char *pszName, int iSize, void *pbuf);

extern pfnUserMsgHook pValClass;
extern pfnUserMsgHook pSpecFade;
extern pfnUserMsgHook pResetFade;
extern pfnUserMsgHook pBench;

// oposing force
int hHudColor(const char *pszName, int iSize, void *pbuf);
int hOldWeapon(const char *pszName, int iSize, void *pbuf);
int hSetMenuTeam(const char *pszName, int iSize, void *pbuf);
int hStatsInfo(const char *pszName, int iSize, void *pbuf);
int hStatsPlayer(const char *pszName, int iSize, void *pbuf);
int hTeamFull(const char *pszName, int iSize, void *pbuf);
int hPlayerIcon(const char *pszName, int iSize, void *pbuf);
int hCTFScore(const char *pszName, int iSize, void *pbuf);
int hCustomIcon(const char *pszName, int iSize, void *pbuf);
int hFlagIcon(const char *pszName, int iSize, void *pbuf);
int hFlagTimer(const char *pszName, int iSize, void *pbuf);
int hPlyrBrowse(const char *pszName, int iSize, void *pbuf);

extern pfnUserMsgHook pHudColor;
extern pfnUserMsgHook pOldWeapon;
extern pfnUserMsgHook pSetMenuTeam;
extern pfnUserMsgHook pStatsInfo;
extern pfnUserMsgHook pStatsPlayer;
extern pfnUserMsgHook pTeamFull;
extern pfnUserMsgHook pPlayerIcon;
extern pfnUserMsgHook pCTFScore;
extern pfnUserMsgHook pCustomIcon;
extern pfnUserMsgHook pFlagIcon;
extern pfnUserMsgHook pFlagTimer;
extern pfnUserMsgHook pPlyrBrowse;

// team fortress classic

#endif